version: 0.2

env:
  variables:
    RE: "251622686032.dkr.ecr.us-east-1.amazonaws.com"
    REPOSITORY_NAME: "YOUR_REPO_NAME"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $RE
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $RE/$REPOSITORY_NAME:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $RE/$REPOSITORY_NAME:latest
