version: 0.2

env:
  variables:
    RE: "251622686032.dkr.ecr.us-east-1.amazonaws.com"
    REPOSITORY_NAME: "logicworks-app"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $RE
      - echo "Checking files in current directory:"
      - ls -R
  build:
    commands:
      - echo Building the Docker image...
      # Added -f Dockerfile to be explicit
      - docker build -t $RE/$REPOSITORY_NAME:latest -f Dockerfile .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $RE/$REPOSITORY_NAME:latest
      - echo Writing image definitions file...
      - printf '[{"name":"logicworks-app","imageUri":"%s"}]' "$RE/$REPOSITORY_NAME:latest" > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
